import { useRef, useState } from "react";
import { BatteryCharging, Cable, ChevronRight, ExternalLink, Gauge, RadioTower, ShieldCheck, ShoppingBag, Wrench } from "lucide-react";

type GearCategory = "Tools and supplies" | "Test equipment" | "Cable and fault location" | "Job comfort and power";
type GearFilter = "All" | GearCategory | "USA made";

type Gear = {
  category: GearCategory;
  name: string;
  model: string;
  bestFor: string;
  note: string;
  amazonUrl: string;
  manufacturerUrl: string;
  imageUrl?: string;
  budget?: boolean;
  usaMade?: boolean;
  certification?: string;
};

export const GEAR_RECOMMENDATIONS: Gear[] = [
  { category: "Tools and supplies", name: "Daniels Manufacturing AF8", model: "M22520/1-01 crimp frame", bestFor: "Qualified machined-contact crimping with the approved turret or positioner.", note: "Match the contact family, setting, locator, and work instruction.", amazonUrl: "https://www.amazon.com/dp/B09CV54JPN?tag=beckify-20", manufacturerUrl: "https://dmctools.com/af8-af8" },
  { category: "Tools and supplies", name: "KNIPEX EvoStrip", model: "Automatic wire stripper", bestFor: "Repeatable conductor preparation in its specified range.", note: "Confirm conductor size, insulation type, and strip length first.", amazonUrl: "https://www.amazon.com/dp/B000R895YM?tag=beckify-20", manufacturerUrl: "https://www.knipex.com/evostrip" },
  { category: "Tools and supplies", name: "Klein Tools 11055", model: "Wire stripper and cutter", bestFor: "Everyday copper-conductor stripping and cutting.", note: "A practical general wiring tool, not qualified contact-crimp tooling.", amazonUrl: "https://www.amazon.com/dp/B00080DPNQ?tag=beckify-20", manufacturerUrl: "https://www.kleintools.com/catalog/wire-strippers-cutters-and-crimpers/wire-stripper-and-cutter-self-opening", budget: true },
  { category: "Tools and supplies", name: "Klein Tools 63050", model: "High-leverage cable cutter", bestFor: "Clean copper, aluminum, and communications-cable cuts before termination.", note: "Verify capacity; never use on energized cable.", amazonUrl: "https://www.amazon.com/dp/B0000302X1?tag=beckify-20", manufacturerUrl: "https://www.kleintools.com/catalog/standard-cable-cutters/cable-cutter", usaMade: true },
  { category: "Tools and supplies", name: "Wiha TorqueVario-S 28506", model: "Adjustable 10-50 in-lb torque driver", bestFor: "Controlled low-torque fastening on terminals and electronics hardware.", note: "Set torque from approved assembly data.", amazonUrl: "https://www.amazon.com/dp/B002QV0FCY?tag=beckify-20", manufacturerUrl: "https://www.wihatools.com/products/adjustable-torquevario-10-50-in-lbs", imageUrl: "https://www.wihatools.com/cdn/shop/files/xj95dmdb06vc5pvonoun_165x.jpg?v=1776759870" },
  { category: "Tools and supplies", name: "Scotch Super 33+", model: "3/4 in x 66 ft vinyl electrical tape", bestFor: "A durable general-purpose tape for electrical insulation and harness finishing.", note: "Use the approved splice or termination method; tape is not a substitute for it.", amazonUrl: "https://www.amazon.com/dp/B01N3D2AFK?tag=beckify-20", manufacturerUrl: "https://www.scotchbrand.com/3M/en_US/p/d/b10014694/", usaMade: true },
  { category: "Tools and supplies", name: "CHANNELLOCK 338CB", model: "8 in high-leverage diagonal cutting pliers", bestFor: "General cutting where durable, comfortable hand pliers are needed.", note: "Not an insulated tool or a substitute for an approved cable cutter.", amazonUrl: "https://www.amazon.com/dp/B00004SBDD?tag=beckify-20", manufacturerUrl: "https://www.channellock.com/product/338cb/", usaMade: true },

  { category: "Test equipment", name: "Fluke 87V", model: "True-RMS industrial multimeter", bestFor: "Primary voltage, resistance, continuity, and frequency troubleshooting.", note: "Prove the meter on a known source before and after a critical test.", amazonUrl: "https://www.amazon.com/dp/B0002YFD1K?tag=beckify-20", manufacturerUrl: "https://www.fluke.com/en-us/product/electrical-testing/digital-multimeters/fluke-87v", imageUrl: "https://media.fluke.com/2725d18d-633b-40b2-b09b-b108002e4d59_product_slideshow_main.jpg" },
  { category: "Test equipment", name: "Fluke 117", model: "Electrician's True-RMS multimeter", bestFor: "Routine building electrical measurements where LoZ helps reduce ghost voltages.", note: "Use leads and the meter only within their marked category and voltage rating.", amazonUrl: "https://www.amazon.com/dp/B000O3LUEI?tag=beckify-20", manufacturerUrl: "https://www.fluke.com/en-us/product/electrical-testing/digital-multimeters/fluke-117", imageUrl: "https://media.fluke.com/e55511c8-92e6-46b2-b9ae-b108002dd7fa_product_slideshow_main.jpg" },
  { category: "Test equipment", name: "Klein Tools MM400", model: "Auto-ranging 600 V digital multimeter", bestFor: "Cost-conscious general electrical measurement in its marked CAT III 600 V scope.", note: "Check supplied leads, fuses, category rating, and procedure before use.", amazonUrl: "https://www.amazon.com/dp/B018EXZO8M?tag=beckify-20", manufacturerUrl: "https://www.kleintools.com/catalog/multimeters/digital-multimeter-auto-ranging-600v", budget: true },
  { category: "Test equipment", name: "Fluke T6-1000", model: "FieldSense electrical tester", bestFor: "Fast AC voltage and current checks at distribution equipment.", note: "Use it within the approved test process, not as a substitute for procedure.", amazonUrl: "https://www.amazon.com/dp/B076DYBHCW?tag=beckify-20", manufacturerUrl: "https://www.fluke.com/en-us/product/electrical-testing/basic-testers/fluke-t6-1000" },
  { category: "Test equipment", name: "Fluke 2AC Alert", model: "90-1000 V AC non-contact voltage tester", bestFor: "A preliminary indication of AC voltage presence.", note: "A non-contact tester cannot establish absence of voltage on its own.", amazonUrl: "https://www.amazon.com/dp/B004I9J4DI?tag=beckify-20", manufacturerUrl: "https://www.fluke.com/en-us/product/electrical-testing/voltage-detectors/fluke-2ac" },
  { category: "Test equipment", name: "Klein Tools NCVT2P", model: "Dual-range non-contact voltage tester", bestFor: "Quick AC presence checks before a complete test.", note: "Verify operation on a known live source first.", amazonUrl: "https://www.amazon.com/dp/B07L5N8ZWS?tag=beckify-20", manufacturerUrl: "https://www.kleintools.com/catalog/electrical-testers/non-contact-voltage-tester-pen-dual-range-12-1000v-ac-or-48-1000v-ac" },
  { category: "Test equipment", name: "Klein Tools ET310", model: "Circuit-breaker finder with GFCI tester", bestFor: "Locating a 90-120 V branch-circuit breaker and checking a grounded receptacle.", note: "It is not a switchgear fault-investigation instrument.", amazonUrl: "https://www.amazon.com/dp/B07QNMCVWP?tag=beckify-20", manufacturerUrl: "https://www.kleintools.com/catalog/electrical-testers/digital-circuit-breaker-finder-gfci-outlet-tester", budget: true },
  { category: "Test equipment", name: "Fluke 62 MAX+", model: "Dual-laser IR thermometer", bestFor: "Screening energized equipment for abnormal temperature.", note: "Emissivity, distance, loading, and follow-up measurement determine whether a finding matters.", amazonUrl: "https://www.amazon.com/dp/B0089N2ZH6?tag=beckify-20", manufacturerUrl: "https://www.fluke.com/en-us/product/temperature-measurement/ir-thermometers/fluke-62-max-plus" },
  { category: "Test equipment", name: "FLIR C5", model: "160 x 120 compact thermal camera", bestFor: "Documenting thermal anomalies on panels, terminations, motors, and equipment under load.", note: "A thermal image identifies a condition to investigate, not the root cause.", amazonUrl: "https://www.amazon.com/dp/B0892MZZT1?tag=beckify-20", manufacturerUrl: "https://www.flir.com/products/c5/" },
  { category: "Test equipment", name: "Fluke 1507", model: "50 V to 1000 V insulation resistance tester", bestFor: "Specified insulation-resistance workflows on wiring and electrical equipment.", note: "Test voltage, isolation, discharge, and acceptance criteria come from the procedure.", amazonUrl: "https://www.amazon.com/dp/B000X4O9WI?tag=beckify-20", manufacturerUrl: "https://www.fluke.com/en-us/product/electrical-testing/insulation-testers/fluke-1507", imageUrl: "https://media.fluke.com/2882fbd6-a477-4823-8210-b108002ddc22_product_slideshow_main.jpg" },
  { category: "Test equipment", name: "Klein Tools ET600", model: "1000 V insulation resistance tester", bestFor: "Insulation, continuity, and voltage measurements in electrical maintenance.", note: "Never insulation-test an energized circuit.", amazonUrl: "https://www.amazon.com/dp/B07ZZX5TK8?tag=beckify-20", manufacturerUrl: "https://www.kleintools.com/catalog/multimeters/insulation-resistance-tester" },
  { category: "Test equipment", name: "Fluke 376 FC", model: "True-RMS AC/DC clamp meter with iFlex", bestFor: "Current checks around conductors where a fixed jaw cannot reach.", note: "Confirm conductor placement and method before interpreting the result.", amazonUrl: "https://www.amazon.com/dp/B017OVC2QM?tag=beckify-20", manufacturerUrl: "https://www.fluke.com/en-us/product/electrical-testing/clamp-meters/fluke-376-fc", imageUrl: "https://media.fluke.com/2349e539-9d7a-457b-b8ea-b108002e1bc3_product_slideshow_main.jpg" },
  { category: "Test equipment", name: "Klein Tools CL120", model: "400 A AC auto-ranging clamp meter", bestFor: "Cost-conscious AC-current, voltage, resistance, and continuity checks.", note: "This clamp measures AC current only; confirm the function before use.", amazonUrl: "https://www.amazon.com/dp/B08CP6GL49?tag=beckify-20", manufacturerUrl: "https://www.kleintools.com/catalog/clamp-meters/digital-clamp-meter-ac-auto-ranging-400-amp", budget: true },
  { category: "Test equipment", name: "Fluke 323", model: "True-RMS 400 A AC clamp meter", bestFor: "Basic AC-current, voltage, and resistance checks.", note: "It measures AC current, not DC current.", amazonUrl: "https://www.amazon.com/dp/B00AQKIEXY?tag=beckify-20", manufacturerUrl: "https://www.fluke.com/en-us/product/electrical-testing/clamp-meters/fluke-323" },
  { category: "Test equipment", name: "Fluke 771", model: "Milliamp process clamp meter", bestFor: "Measuring 4-20 mA process signals without opening the loop.", note: "Confirm loop configuration and access requirements before clamping.", amazonUrl: "https://www.amazon.com/dp/B000R81ARM?tag=beckify-20", manufacturerUrl: "https://www.fluke.com/en-us/product/process-calibration-tools/loop-calibrators/fluke-771" },
  { category: "Test equipment", name: "RIGOL DHO804", model: "Four-channel 70 MHz digital oscilloscope", bestFor: "Bench diagnostics for power rails, clocks, data, and control signals.", note: "Probe selection and grounding still matter.", amazonUrl: "https://www.amazon.com/dp/B0CGHQHQN7?tag=beckify-20", manufacturerUrl: "https://mall.rigol.com/shiboqi/dho804.html" },
  { category: "Test equipment", name: "RIGOL DS1054Z", model: "Four-channel 50 MHz digital oscilloscope", bestFor: "General embedded, control, and low-to-mid-speed waveform troubleshooting.", note: "Never create a fault path with a grounded probe.", amazonUrl: "https://www.amazon.com/dp/B012938E76?tag=beckify-20", manufacturerUrl: "https://www.rigolna.com/products/digital-oscilloscopes/ds1000z/", budget: true },
  { category: "Test equipment", name: "SIGLENT SDS1104X-E", model: "Four-channel 100 MHz digital oscilloscope", bestFor: "Electronics work that benefits from more bandwidth and signal comparison.", note: "Verify probe compensation, attenuation, and ground reference first.", amazonUrl: "https://www.amazon.com/dp/B0771N1ZF9?tag=beckify-20", manufacturerUrl: "https://siglentna.com/product/sds1104x-e-100-mhz/" },
  { category: "Test equipment", name: "Fluke 289", model: "True-RMS logging multimeter with TrendCapture", bestFor: "Finding intermittent behavior through logged measurements.", note: "Use logs to support a diagnostic plan, not to replace required calibration.", amazonUrl: "https://www.amazon.com/dp/B0012B51HI?tag=beckify-20", manufacturerUrl: "https://www.fluke.com/en-us/product/electrical-testing/digital-multimeters/fluke-289", imageUrl: "https://media.fluke.com/754f67ca-87e2-4668-bbff-b108002c0c74_product_slideshow_main.jpg" },

  { category: "Cable and fault location", name: "Megger TDR500/3", model: "Handheld cable fault locator", bestFor: "Locating opens, shorts, and distance-to-fault on de-energized metallic cable.", note: "Isolate and de-energize the cable before connecting a TDR.", amazonUrl: "https://www.amazon.com/dp/B00EPLIEJO?tag=beckify-20", manufacturerUrl: "https://www.megger.com/" },
  { category: "Cable and fault location", name: "Klein Tools Scout Pro 3", model: "VDV501-851 cable tester kit", bestFor: "Identifying and mapping Ethernet, telephone, and coaxial cable runs.", note: "It is a verifier, not a certification instrument.", amazonUrl: "https://www.amazon.com/dp/B085LPN71C?tag=beckify-20", manufacturerUrl: "https://www.kleintools.com/catalog/cable-testers/scout-pro-3-tester-kit" },
  { category: "Cable and fault location", name: "Fluke Networks MicroScanner PoE", model: "MS-POE copper cable verifier", bestFor: "PoE, wiremap, length, switch capability, and distance-to-fault checks.", note: "For supported copper Ethernet systems only.", amazonUrl: "https://www.amazon.com/dp/B07NJMKG9L?tag=beckify-20", manufacturerUrl: "https://www.fluke.com/en-us/product/network-cable-testers/copper/ms-poe" },
  { category: "Cable and fault location", name: "AURSINC NanoVNA-H4", model: "9 kHz to 1.5 GHz portable vector network analyzer", bestFor: "Antenna, coax, impedance, and return-loss investigation.", note: "Not a calibrated replacement where traceability is required.", amazonUrl: "https://www.amazon.com/dp/B07T6LXNTV?tag=beckify-20", manufacturerUrl: "https://nanovna.com/", budget: true },

  { category: "Job comfort and power", name: "EcoFlow DELTA Pro 3", model: "4096 Wh portable power station", bestFor: "Quiet jobsite, outage, and remote-work power where portable 120/240 V capacity is appropriate.", note: "EcoFlow describes this model as UL 9540 certified. Verify the current label, configuration, and local requirements before installation.", amazonUrl: "https://www.amazon.com/dp/B0D14FMFZD?tag=beckify-20", manufacturerUrl: "https://us.ecoflow.com/products/delta-pro-3-portable-power-station", certification: "UL 9540 certified" },
  { category: "Job comfort and power", name: "SeeDevil 150 W Balloon Light Kit", model: "150 W, 19,500 lm portable area light", bestFor: "Glare-reduced, wide-area task lighting for night work and temporary sites.", note: "Plan the 120 V feed, tripod placement, and required site lighting controls.", amazonUrl: "https://www.amazon.com/dp/B081277RB5?tag=beckify-20", manufacturerUrl: "https://seedevil.com/collections/light-fixtures" },
  { category: "Job comfort and power", name: "BougeRV 23 Quart Portable Fridge", model: "12 V compressor cooler", bestFor: "Keeping food, drinks, or permitted temperature-sensitive supplies cold on long field days.", note: "Use the supplied power arrangement and protect the vehicle battery.", amazonUrl: "https://www.amazon.com/dp/B08G1BBBQW?tag=beckify-20", manufacturerUrl: "https://www.bougerv.com/products/12v-23-quart-portable-refrigerator-for-travel" },
  { category: "Job comfort and power", name: "HOTLIGH Magnetic Flashlight", model: "ZF6771 rechargeable magnetic work light", bestFor: "Close-up, hands-free light at panels, cabinets, and service points.", note: "This is convenience lighting, not a hazardous-location light.", amazonUrl: "https://www.amazon.com/dp/B0D66SHL2C?tag=beckify-20", manufacturerUrl: "https://hotligh.com/" },
  { category: "Job comfort and power", name: "TORRAS COOLiFY 2S", model: "Wearable neck air conditioner", bestFor: "Personal cooling during hot outdoor, rooftop, and vehicle work.", note: "Treat it as comfort gear; maintain heat-stress breaks, hydration, and the site plan.", amazonUrl: "https://www.amazon.com/dp/B0BY9271YQ?tag=beckify-20", manufacturerUrl: "https://coolify.torraslife.com/collections/all-products" },
];

const categoryGuides: { filter: GearFilter; label: string; description: string; icon: typeof Wrench }[] = [
  { filter: "All", label: "All gear", description: "Every recommendation", icon: Wrench },
  { filter: "Tools and supplies", label: "Tools & supplies", description: "Cut, strip, torque, tape", icon: Wrench },
  { filter: "Test equipment", label: "Test equipment", description: "Measure and diagnose", icon: Gauge },
  { filter: "Cable and fault location", label: "Cable & fault location", description: "Trace, verify, and locate", icon: Cable },
  { filter: "Job comfort and power", label: "Job comfort & power", description: "Light, power, cool, and store", icon: BatteryCharging },
  { filter: "USA made", label: "USA made", description: "Manufacturer-identified U.S. products", icon: ShieldCheck },
];

function getGearIcon(category: GearCategory) {
  if (category === "Tools and supplies") return Wrench;
  if (category === "Test equipment") return Gauge;
  if (category === "Cable and fault location") return RadioTower;
  return BatteryCharging;
}

function ProductVisual({ item }: { item: Gear }) {
  const Icon = getGearIcon(item.category);

  if (item.imageUrl) {
    return <figure className="mt-4 overflow-hidden rounded-xl border border-[var(--border)] bg-white/95"><div className="h-36 p-3"><img src={item.imageUrl} alt={item.name} loading="lazy" className="h-full w-full object-contain" /></div><figcaption className="border-t border-[var(--border)] px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-500">Official product photo</figcaption></figure>;
  }

  return <div className="relative mt-4 flex h-36 items-center overflow-hidden rounded-xl border border-cyan-300/15 bg-[#07101c] p-5" role="img" aria-label={`${item.name} product reference`}>
    <div className="absolute inset-0 opacity-40" style={{ backgroundImage: "linear-gradient(rgba(88,142,185,.18) 1px, transparent 1px), linear-gradient(90deg, rgba(88,142,185,.18) 1px, transparent 1px)", backgroundSize: "20px 20px" }} />
    <svg viewBox="0 0 480 144" className="absolute inset-0 h-full w-full" aria-hidden="true"><path d="M0 104h88l24-25h72l24 25h88l25-25h159" fill="none" stroke="#5ed7ff" strokeOpacity=".42" strokeWidth="2" /><path d="M8 42h76l18 18h66l18-35h84l18 35h70l20-18h112" fill="none" stroke="#9d7cff" strokeOpacity=".38" strokeWidth="2" /></svg>
    <div className="relative flex items-center gap-4"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl border border-cyan-200/30 bg-[#0a1b2c]"><Icon className="h-7 w-7 text-cyan-200" aria-hidden="true" /></span><span><span className="block text-[10px] font-bold uppercase tracking-[0.16em] text-cyan-200/70">Product reference</span><span className="mt-1 block font-mono text-sm font-semibold leading-5 text-slate-100">{item.model}</span></span></div>
  </div>;
}

export function GearMatrix() {
  const [filter, setFilter] = useState<GearFilter>("All");
  const catalogRef = useRef<HTMLDivElement>(null);
  const visible = GEAR_RECOMMENDATIONS.filter((item) => filter === "All" || (filter === "USA made" ? item.usaMade : item.category === filter));
  const selectCategory = (nextFilter: GearFilter) => {
    setFilter(nextFilter);
    requestAnimationFrame(() => catalogRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }));
  };
  const countFor = (nextFilter: GearFilter) => GEAR_RECOMMENDATIONS.filter((item) => nextFilter === "All" || (nextFilter === "USA made" ? item.usaMade : item.category === nextFilter)).length;
  const title = filter === "All" ? "All recommended gear" : filter;

  return <section className="space-y-7" aria-labelledby="gear-title">
    <header className="border-b border-[var(--border)] pb-7"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent)]">Recommended gear</p><h1 id="gear-title" className="mt-2 max-w-3xl font-display text-4xl font-bold md:text-5xl">Tools, supplies, and field gear worth buying.</h1><p className="mt-4 max-w-2xl text-[var(--muted)]">Industry-standard picks for electrical work, cable troubleshooting, field power, and job comfort. Every Amazon button goes to the exact model.</p></header>

    <section aria-labelledby="category-map-title"><div className="mb-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent)]">Shop by category</p><h2 id="category-map-title" className="mt-1 font-display text-2xl font-bold">Choose what you need.</h2></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{categoryGuides.map((guide) => { const Icon = guide.icon; const active = filter === guide.filter; return <button key={guide.filter} type="button" aria-pressed={active} onClick={() => selectCategory(guide.filter)} className={`group flex items-center gap-3 rounded-xl border p-4 text-left transition ${active ? "border-[var(--accent)] bg-[var(--accent-soft)]" : "border-[var(--border)] bg-[var(--surface)] hover:border-[var(--accent)]/60 hover:bg-white/[0.025]"}`}><span className="rounded-lg bg-[var(--accent-soft)] p-2"><Icon className="h-5 w-5 text-[var(--accent)]" aria-hidden="true" /></span><span className="min-w-0 flex-1"><span className="block font-display text-base font-bold text-[var(--foreground)]">{guide.label}</span><span className="mt-0.5 block text-xs text-[var(--muted)]">{guide.description} · {countFor(guide.filter)}</span></span><ChevronRight className="h-4 w-4 shrink-0 text-[var(--accent)] transition group-hover:translate-x-0.5" aria-hidden="true" /></button>; })}</div></section>

    <div className="flex gap-3 border-l-2 border-amber-400/70 bg-amber-400/5 px-4 py-3 text-sm leading-6 text-[var(--muted)]"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-amber-300" aria-hidden="true" /><p className="m-0">Use approved procedures, ratings, and calibration requirements. These recommendations support the work; they do not replace them.</p></div>
    <p className="text-xs text-[var(--muted)]">Disclosure: As an Amazon Associate I earn from qualifying purchases. Amazon buttons are paid links.</p>

    <div ref={catalogRef} className="scroll-mt-6"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent)]">Product list</p><h2 className="mt-1 font-display text-2xl font-bold">{title}</h2></div>{filter !== "All" && <button type="button" onClick={() => setFilter("All")} className="rounded-full border border-[var(--border)] px-3 py-1.5 text-xs font-semibold text-[var(--muted)] transition hover:border-[var(--accent)] hover:text-[var(--accent)]">Show all {GEAR_RECOMMENDATIONS.length} products</button>}</div><div className="grid gap-4 md:grid-cols-2">{visible.map((item) => { const Icon = getGearIcon(item.category); return <article className="card-surface flex flex-col p-5" key={item.name}><div className="flex items-start justify-between gap-4"><span className="rounded-xl bg-[var(--accent-soft)] p-3"><Icon className="h-5 w-5 text-[var(--accent)]" aria-hidden="true" /></span><span className="flex flex-wrap justify-end gap-1.5 text-right text-[10px] font-bold uppercase tracking-[0.12em]"><span className="text-[var(--muted)]">{item.category}</span>{item.usaMade && <span className="rounded-full bg-blue-300/10 px-2 py-1 text-blue-200">USA made</span>}{item.budget && <span className="rounded-full bg-amber-300/10 px-2 py-1 text-amber-200">Budget pick</span>}{item.certification && <span className="rounded-full bg-emerald-300/10 px-2 py-1 text-emerald-200">{item.certification}</span>}</span></div><ProductVisual item={item} /><h3 className="mt-4 font-display text-xl font-bold">{item.name}</h3><p className="mt-1 text-xs font-semibold uppercase tracking-[0.12em] text-[var(--muted)]">{item.model}</p><p className="mt-4 text-sm font-semibold leading-6">{item.bestFor}</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.note}</p><div className="mt-5 flex flex-wrap items-center gap-3 text-sm font-semibold"><a href={item.amazonUrl} target="_blank" rel="sponsored noopener noreferrer" aria-label={`View the exact ${item.name} model on Amazon (paid link)`} className="inline-flex items-center gap-2 rounded-lg bg-[var(--accent)] px-4 py-2.5 text-[var(--accent-foreground)] transition hover:bg-[var(--accent-2)]"><ShoppingBag className="h-4 w-4" /> View exact model on Amazon <ExternalLink className="h-3.5 w-3.5" /></a><a href={item.manufacturerUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 px-1 py-2 text-[var(--muted)] transition hover:text-[var(--accent)] hover:underline">Manufacturer specs <ExternalLink className="h-3.5 w-3.5" /></a></div></article>; })}</div></div>
  </section>;
}
