import { useState } from "react";
import { Cable, CheckCircle2, ClipboardCheck, Gauge, Search, Wrench } from "lucide-react";

type Gear = { category: "Wire Termination" | "Bench Prototyping" | "Field Diagnostics"; name: string; justification: string; use: string; link: string };
const gear: Gear[] = [
  { category: "Wire Termination", name: "Controlled-cycle ratchet crimper", justification: "A full-cycle mechanism prevents a partial crimp and gives the terminal a repeatable compression profile across a known wire range.", use: "Reliable insulated and non-insulated terminal work", link: "https://www.molex.com/" },
  { category: "Wire Termination", name: "Ferrule and terminal inspection gauge", justification: "A visual and dimensional check catches incomplete insertion, bell-mouth damage, and insulation trapped in the barrel before the conductor is energized.", use: "Fast post-crimp quality control", link: "https://www.phoenixcontact.com/" },
  { category: "Bench Prototyping", name: "Current-limited bench supply", justification: "Adjustable current limiting makes first power-up a controlled experiment instead of a smoke test with paperwork afterward.", use: "Bring-up, fault isolation, and load checks", link: "https://www.keysight.com/" },
  { category: "Bench Prototyping", name: "True-RMS handheld multimeter", justification: "True-RMS measurement is the honest choice for non-sinusoidal waveforms and switching supplies where average-responding meters can lie politely.", use: "Voltage, resistance, continuity, and AC measurements", link: "https://www.fluke.com/" },
  { category: "Field Diagnostics", name: "Insulation resistance tester", justification: "A megohmmeter applies a defined test voltage and reveals leakage that a continuity beep will confidently miss.", use: "Cable insulation and motor winding checks", link: "https://www.megger.com/" },
  { category: "Field Diagnostics", name: "Clamp meter with inrush capture", justification: "Inrush capture shows what a motor or transformer demands at startup without breaking the circuit to insert a meter.", use: "Startup current and live load verification", link: "https://www.fluke.com/" },
];
const categories = ["All", "Wire Termination", "Bench Prototyping", "Field Diagnostics"] as const;

export function GearMatrix() {
  const [category, setCategory] = useState<(typeof categories)[number]>("All"); const [query, setQuery] = useState("");
  const visible = gear.filter((item) => (category === "All" || item.category === category) && `${item.name} ${item.justification} ${item.use}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="space-y-6" aria-labelledby="gear-title"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent)]">Field kit</p><h1 id="gear-title" className="mt-2 font-display text-4xl font-bold">Recommended tools, chosen for the work.</h1><p className="mt-4 max-w-2xl text-[var(--muted)]">A compact matrix for building, terminating, and diagnosing electrical systems. Selection notes explain the engineering reason, not just the logo.</p></div><div className="card-surface flex flex-col gap-4 p-4 md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap gap-2">{categories.map((item) => <button type="button" key={item} onClick={() => setCategory(item)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold transition-colors ${category === item ? "border-[var(--accent)] bg-[var(--accent-soft)] text-[var(--accent)]" : "border-[var(--border)] text-[var(--muted)] hover:text-[var(--foreground)]"}`}>{item}</button>)}</div><label className="flex items-center gap-2 rounded-lg border border-[var(--border)] px-3 py-2"><Search className="h-4 w-4 text-[var(--muted)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter tools" className="w-full bg-transparent text-sm outline-none placeholder:text-[var(--muted)] md:w-48" aria-label="Filter recommended tools" /></label></div><div className="grid gap-4 md:grid-cols-2">{visible.map((item) => { const Icon = item.category === "Wire Termination" ? Cable : item.category === "Bench Prototyping" ? Wrench : Gauge; return <article className="card-surface flex flex-col p-6" key={item.name}><div className="flex items-start justify-between gap-4"><div className="rounded-xl bg-[var(--accent-soft)] p-3"><Icon className="h-5 w-5 text-[var(--accent)]" /></div><span className="text-right text-[10px] font-bold uppercase tracking-[0.14em] text-[var(--muted)]">{item.category}</span></div><h2 className="mt-5 font-display text-xl font-bold">{item.name}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.justification}</p><div className="mt-4 flex items-start gap-2 text-xs text-[var(--foreground)]"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[var(--accent)]" /> {item.use}</div><a href={item.link} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[var(--accent)] hover:underline">Check manufacturer details <ClipboardCheck className="h-4 w-4" /></a></article>; })}</div><p className="rounded-xl border border-[var(--border)] bg-black/15 p-4 text-xs leading-5 text-[var(--muted)]"><strong className="text-[var(--foreground)]">FTC affiliate disclosure:</strong> Beckify may earn a commission if you purchase through a future affiliate link. Recommendations are based on technical fit and field use, not commission amount. Manufacturer links above are informational and are not affiliate links.</p></section>;
}
