/**
 * Aperiodic Penrose P3 tiling used as a fixed, very-low-contrast page texture.
 *
 * The tiling itself lives in public/penrose.svg, generated by
 * scripts/generate-penrose.mjs via Robinson-triangle deflation. Shipping it as
 * a cached static asset rather than building it in JS keeps it out of the
 * bundle and lets the standalone /toolbox app reuse the exact same artwork.
 *
 * BASE_URL keeps the path correct whatever base the site is built under.
 */
export const PenroseField = () => (
  <img
    src={`${import.meta.env.BASE_URL}penrose.svg`}
    className="penrose-field"
    alt=""
    aria-hidden="true"
    draggable={false}
  />
);
