import { FadeIn } from "@/components/FadeIn";

const media = {
  motor: "/projects/vespa/journal/hub-motor.jpg",
  rear: "/projects/vespa/studio/rear-hub-detail.jpg",
  controller: "/projects/vespa/studio/controller-install.jpg",
  pack: "/projects/vespa/journal/pack-test.jpg",
  cells: "/projects/vespa/journal/cell-stack.jpg",
};

const cardStyle = { background: "#efe6d7", padding: ".75rem" } as const;

export function TopSpeedEstimate() {
  return <FadeIn><section className="journal-section" id="top-speed" aria-labelledby="top-speed-title"><div className="section-heading"><p className="section-index">08 / speed estimate</p><h2 id="top-speed-title">Estimate speed from road load.</h2><p>Use aerodynamic drag plus rolling resistance, then solve for speed at available wheel power. It is an estimate—not a replacement for a GPS test.</p></div><div style={{ marginTop: "2rem", borderTop: "2px solid #1d2421", paddingTop: "1rem" }}><code style={{ display: "block", fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: "clamp(.9rem,2vw,1.15rem)", overflowX: "auto" }}>Pwheel = ½ρCdA·v³ + Crr·m·g·v</code><p className="photo-caption">For this model: rider 150 lb, scooter assumed 220 lb, CdA 0.60 m², Crr 0.018, air density 1.225 kg/m³, and 85% electrical-to-wheel efficiency. That yields ~44 mph at 4 kW and ~57 mph at 8 kW peak. The observed 55 mph is real; terminal speed was not reached.</p></div></section></FadeIn>;
}

export function MotorGuide() {
  return <FadeIn><section className="journal-section" id="motor-guide" aria-labelledby="motor-guide-title"><div className="section-heading"><p className="section-index">09 / motor guide</p><h2 id="motor-guide-title">Direct-drive hub motor: what it changes.</h2><p>The QS motor places the rotor in the wheel and fixes the stator to the axle. Torque arrives at the wheel without a chain, belt, clutch, or reduction gearbox.</p></div><div className="story-grid" style={{ marginTop: "2.5rem" }}><figure className="story-media"><img src={media.rear} alt="Direct-drive hub motor and rear disc brake detail" /><figcaption>Wheel, direct-drive hub motor, brake rotor, caliper, and fabricated suspension structure.</figcaption></figure><div className="story-copy"><h2 style={{ fontSize: "clamp(1.7rem,3vw,2.6rem)" }}>Hub motor versus other layouts</h2><table style={{ minWidth: 0 }}><thead><tr><th>Layout</th><th>Why choose it</th><th>Trade-off</th></tr></thead><tbody><tr><td><strong>Direct hub</strong></td><td>Simple driveline; compact packaging; no final-drive maintenance</td><td>More unsprung mass; wheel torque and cooling are motor-limited</td></tr><tr><td><strong>Mid-drive + reduction</strong></td><td>Gear reduction can multiply wheel torque; motor mass stays sprung</td><td>Chain/belt, sprockets, alignment, guards, and more moving parts</td></tr><tr><td><strong>Central motor + gearbox</strong></td><td>Can retain multiple ratios and broad operating range</td><td>Most complex packaging and control integration</td></tr></tbody></table><details style={{ marginTop: "1.25rem" }}><summary style={{ cursor: "pointer", fontWeight: 700 }}>Torque and RPM context</summary><div style={cardStyle}><p><strong>Stock reference.</strong> Using approximately 10 bhp / 7.5 kW at a representative 5,700 rpm power peak gives about 12.6 N·m at the crank: T = 9550P/n. The stock gearbox and final drive multiply that before it reaches the tire; exact wheel torque needs the actual gear ratios and engine torque curve.</p><p><strong>This build.</strong> With an estimated 0.216 m rolling radius, 55 mph corresponds to roughly 1,090 wheel rpm. At that speed, T = 9550P/n gives ~35 N·m at 4 kW and ~70 N·m at 8 kW, before losses. This is wheel-side torque in direct drive, not a stall-torque claim. Actual low-speed torque requires the motor torque constant and controller phase-current limit, which are not in the supplied documentation.</p></div></details></div></div></section></FadeIn>;
}

export function SafetyGuide() {
  return <FadeIn><section className="journal-section" id="safety" aria-labelledby="safety-title"><div className="section-heading"><p className="section-index">10 / safe build sequence</p><h2 id="safety-title">Build deliberately. Test in stages.</h2><p>High voltage, rotating machinery, and braking modifications deserve a documented inspection—not a single first ride.</p></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(15rem,1fr))", gap: "1rem", marginTop: "2.5rem" }}><details open style={cardStyle}><summary style={{ cursor: "pointer", fontWeight: 700 }}>Before energizing</summary><p>Confirm cell-group voltage order, BMS sense-lead sequence, insulation barriers, fuse/breaker, contactor, precharge path, polarity, cable strain relief, and a reachable service disconnect.</p></details><details style={cardStyle}><summary style={{ cursor: "pointer", fontWeight: 700 }}>Bench test first</summary><p>Lift the drive wheel, limit current, verify throttle zero, brake cut-off, direction, emergency isolation, current display, and motor temperature. Log pack voltage before and after each step.</p></details><details style={cardStyle}><summary style={{ cursor: "pointer", fontWeight: 700 }}>Mechanical inspection</summary><p>Torque-mark critical fasteners, check axle retention, rotor runout, caliper clearance, hose routing, suspension travel, tire clearance, and stand/center-stand interference.</p></details><details style={cardStyle}><summary style={{ cursor: "pointer", fontWeight: 700 }}>Road test progression</summary><p>Begin with low-speed brake tests in a controlled area. Increase current and speed only after checking connectors, interconnects, controller, motor, and brake temperatures.</p></details></div></section></FadeIn>;
}

export function PartsGallery() {
  const cards = [[media.motor, "QS 10-inch hub motor", "Direct-drive traction motor"], [media.controller, "VOTOL EM-100", "Controller and protected power bay"], [media.pack, "20S10P battery pack", "72V nominal / 25Ah"], [media.cells, "Samsung 25R cell layout", "Ten cells per parallel group"], [media.rear, "Rear disc system", "Rotor, caliper, and structure"]] as const;
  return <FadeIn><section className="journal-section" id="parts-gallery" aria-labelledby="parts-gallery-title"><div className="section-heading"><p className="section-index">11 / parts in context</p><h2 id="parts-gallery-title">The major parts, shown in the build.</h2><p>Use the linked parts table for purchasing references; this gallery makes it easier to identify where the major systems sit in the scooter.</p></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(13rem,1fr))", gap: "1rem", marginTop: "2.5rem" }}>{cards.map(([src, title, caption]) => <figure key={title} style={{ margin: 0 }}><img src={src} alt={title} style={{ display: "block", width: "100%", height: "14rem", objectFit: "cover" }} /><figcaption className="photo-caption"><strong>{title}</strong><br />{caption}</figcaption></figure>)}</div></section></FadeIn>;
}
