import { Link } from "wouter";
import { AlertTriangle, ArrowLeft, BatteryCharging, Cable, ExternalLink, Gauge, GitBranch, Images, PlayCircle, ShieldCheck, Sparkles, Wrench, Zap } from "lucide-react";
import { Layout } from "@/components/Layout";
import { FadeIn } from "@/components/FadeIn";
import { SchemaHead, SITE_URL } from "@/components/seo/SchemaHead";

const SOURCE_URL = "https://endless-sphere.com/sphere/threads/vespa-p200e-ev-conversion.113986/";
const specs = [
  ["Donor", "Vespa P200E", "Non-running chassis chosen as a useful starting point"],
  ["Battery", "72 V nominal", "200 Samsung INR 18650 25R cells in a 20S10P layout"],
  ["BMS", "Daly 20S / 100 A", "Cell protection and pack-level monitoring"],
  ["Protection", "125 A DC breaker", "Disconnect and last line of defense if the BMS fails to open"],
  ["Switching", "TE contactor + ZEVA precharge", "Controlled connection between the pack and controller"],
  ["Chassis", "Custom swingarm", "Square channel, 4130 tube, bushings, and a mono-shock mount"],
];
const milestones = [
  ["01", "Find the right donor", "A non-running P200E became the foundation after its original engine found another home."],
  ["02", "Solve the mechanical interface", "A hub motor did not match the factory engine mount, so the rear structure had to be fabricated."],
  ["03", "Build the energy system", "The battery, protection, contactor, precharge, and controller became one coordinated electrical system."],
  ["04", "Ride, learn, iterate", "The finished scooter was quick and joyful to ride, while real-world testing exposed the next round of improvements."],
];
const buildPhotos = [
  { src: "/projects/vespa/donor-scooter.jpg", alt: "Green Vespa P200E donor scooter parked outside", caption: "The non-running P200E that became the donor chassis.", size: "feature" },
  { src: "/projects/vespa/swingarm-cad.jpg", alt: "CAD rendering of the custom Vespa swingarm and hub motor", caption: "The first pass at a swingarm that could accept the hub motor." },
  { src: "/projects/vespa/swingarm-fabrication.jpg", alt: "Fabricated metal swingarm on a workbench", caption: "Fabrication turned the CAD idea into a testable part." },
  { src: "/projects/vespa/cell-layout.jpg", alt: "Blue 18650 battery cells arranged into a pack", caption: "Cell groups laid out before the pack was closed up." },
  { src: "/projects/vespa/battery-pack.jpg", alt: "Completed blue lithium battery pack with wiring", caption: "The 20S10P pack, built from 200 Samsung 18650 cells." },
  { src: "/projects/vespa/battery-installed.jpg", alt: "Blue battery pack installed inside the Vespa chassis", caption: "Battery packaging inside the scooter body." },
  { src: "/projects/vespa/first-ride.jpg", alt: "Green electric Vespa during a first ride", caption: "The conversion became a rideable machine." },
  { src: "/projects/vespa/finished-scooter.jpg", alt: "Green Vespa conversion standing outside after assembly", caption: "A finished prototype, ready to leave the workshop." },
  { src: "/projects/vespa/after-collision.jpg", alt: "Vespa chassis and controller after a collision", caption: "The final documentation after the test-ride collision." },
];

function ArchitectureDiagram() {
  return <div className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[#07101a] p-4 md:p-6"><div className="mb-5 flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent)]">System architecture</p><h2 className="mt-1 font-display text-xl font-bold">Energy in, torque out</h2></div><GitBranch className="h-5 w-5 text-[var(--accent)]" /></div><svg viewBox="0 0 920 250" className="h-auto w-full" role="img" aria-label="Electrical architecture from battery through protection and controller to hub motor"><defs><linearGradient id="vespa-flow" x1="0" x2="1"><stop offset="0" stopColor="#8b7bff" /><stop offset="1" stopColor="#35d2bd" /></linearGradient></defs><path d="M170 125H255M395 125H480M620 125H705" stroke="url(#vespa-flow)" strokeWidth="5" strokeLinecap="round" /><path d="M213 125l-12-8v16zm212 0-12-8v16zm212 0-12-8v16z" fill="#35d2bd" /><g fill="#102336" stroke="#8b7bff" strokeWidth="2"><rect x="20" y="74" width="150" height="102" rx="14" /><rect x="255" y="74" width="140" height="102" rx="14" /><rect x="480" y="74" width="140" height="102" rx="14" /><rect x="705" y="74" width="190" height="102" rx="14" /></g><g fill="#eef0fa" fontFamily="Inter, sans-serif" textAnchor="middle"><text x="95" y="112" fontSize="16" fontWeight="700">72 V pack</text><text x="95" y="138" fontSize="12" fill="#9497b8">20S10P · 200 cells</text><text x="325" y="112" fontSize="16" fontWeight="700">Protection</text><text x="325" y="138" fontSize="12" fill="#9497b8">BMS · breaker</text><text x="550" y="112" fontSize="16" fontWeight="700">Power stage</text><text x="550" y="138" fontSize="12" fill="#9497b8">contactor · precharge</text><text x="800" y="112" fontSize="16" fontWeight="700">Votol + hub motor</text><text x="800" y="138" fontSize="12" fill="#9497b8">control becomes motion</text></g><text x="460" y="220" fill="#35d2bd" fontSize="12" textAnchor="middle" letterSpacing="2">MEASURED ENERGY PATH</text></svg></div>;
}

export default function VespaP200EPage() {
  return <Layout><SchemaHead title="Vespa P200E EV Conversion | Beckify" description="A documented Vespa P200E electric conversion: custom swingarm, 72 V 20S10P battery, power electronics, controller integration, rides, and lessons learned." path="/projects/vespa-p200e" type="article" schema={{ "@context": "https://schema.org", "@type": ["TechArticle", "HowTo"], name: "Vespa P200E EV Conversion", headline: "From non-running P200E to a quick 72 V electric scooter", description: "A first-person engineering build log covering the mechanical, electrical, and practical decisions behind a Vespa P200E EV conversion.", url: `${SITE_URL}/projects/vespa-p200e`, author: { "@type": "Person", name: "Trevor Beck" }, about: { "@type": "Product", name: "Vespa P200E EV conversion" } }} />
    <FadeIn><Link href="/projects" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--muted)] transition-colors hover:text-[var(--accent)]"><ArrowLeft className="h-4 w-4" /> Back to projects</Link><div className="mt-8 grid gap-8 lg:grid-cols-[1.35fr_0.65fr] lg:items-end"><div><p className="mb-4 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-[var(--accent)]"><Sparkles className="h-4 w-4" /> Hands-on build log</p><h1 className="max-w-4xl font-display text-4xl font-bold tracking-tight text-[var(--foreground)] md:text-6xl">A Vespa that trades its engine for electrons.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--muted)]">The goal was bigger than making an electric scooter. This was a practical way to learn custom battery construction, power electronics, mechanical fabrication, and control-system integration before taking on the next build.</p></div><div className="card-surface border-[var(--accent)]/30 p-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--muted)]">Build snapshot</p><p className="mt-3 font-display text-3xl font-bold text-[var(--accent)]">72 V</p><p className="mt-1 text-sm text-[var(--muted)]">20S10P lithium pack, custom rear structure, and hub-motor drive.</p><div className="mt-5 flex items-center gap-2 text-xs text-[var(--muted)]"><Gauge className="h-4 w-4 text-[var(--accent)]" /> Quick, responsive, and built to teach.</div></div></div></FadeIn>
    <FadeIn delay={0.08}><div className="grid gap-4 md:grid-cols-4">{milestones.map(([number, title, text]) => <div className="card-surface p-5" key={number}><span className="font-mono text-xs text-[var(--accent)]">{number}</span><h2 className="mt-4 font-display text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{text}</p></div>)}</div></FadeIn>
    <FadeIn delay={0.12}><ArchitectureDiagram /></FadeIn>
    <FadeIn delay={0.14}><section aria-labelledby="vespa-gallery-title"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent)]">Build photography</p><h2 id="vespa-gallery-title" className="mt-2 font-display text-3xl font-bold">The work, not just the wiring diagram.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--muted)]">A visual sequence from donor chassis to battery construction, fabrication, first ride, and the point where the project paused.</p></div><Images className="hidden h-7 w-7 text-[var(--accent)] sm:block" /></div><div className="grid auto-rows-[170px] grid-cols-2 gap-3 md:auto-rows-[190px] md:grid-cols-4">{buildPhotos.map((photo) => <figure className={`group relative overflow-hidden rounded-2xl border border-[var(--border)] bg-[#07101a] ${photo.size === "feature" ? "col-span-2 row-span-2" : ""}`} key={photo.src}><img src={photo.src} alt={photo.alt} loading="lazy" decoding="async" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><figcaption className="absolute inset-x-0 bottom-0 translate-y-0 bg-gradient-to-t from-black/90 via-black/65 to-transparent px-4 pb-3 pt-10 text-xs leading-5 text-white opacity-100 transition duration-300 sm:translate-y-1 sm:opacity-0 sm:group-hover:translate-y-0 sm:group-hover:opacity-100">{photo.caption}</figcaption></figure>)}</div><p className="mt-4 text-xs leading-5 text-[var(--muted)]">Photos from the <a href={SOURCE_URL} target="_blank" rel="noopener noreferrer" className="font-semibold text-[var(--accent)] hover:underline">original build thread</a>. The gallery is a local copy for a faster, more reliable project page.</p></section></FadeIn>
    <FadeIn delay={0.16}><div className="grid gap-8 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent)]">The design brief</p><h2 className="mt-2 font-display text-3xl font-bold">Use the scooter as a systems laboratory.</h2><div className="mt-5 space-y-4 text-[var(--muted)] leading-7"><p>I found a P200E that did not run. Someone else wanted the engine, which made the chassis a good candidate for an electric conversion instead of sending it straight to the scrap pile.</p><p>The project was deliberately educational. Every subsystem had to answer a real question: how do you package a high-current battery, make a hub motor fit where an engine used to live, sequence a contactor safely, and turn a prototype wiring layout into something rideable?</p><p>The result was not a showroom restoration. It was more useful than that: a fast, joyful test platform with honest notes about what worked and what the next revision should fix.</p></div></div><div className="grid gap-4 sm:grid-cols-2">{[[BatteryCharging, "Energy system", "200 Samsung INR 18650 25R cells form a 20S10P pack. Two 0.15 x 5.00 mm nickel strips were used per series connection for the target current."], [Wrench, "Fabrication", "The stock engine mount could not accept a hub motor, so a custom swingarm was built from square channel, 4130 round tube, bushings, and a mono-shock mount."], [Cable, "Controls", "A Votol controller, TE automotive contactor, ZEVA precharge circuit, and 125 A DC breaker created the path from battery to motor."], [ShieldCheck, "Safety mindset", "The BMS protects the pack, while the breaker provides a separate disconnect and overcurrent backstop. The lock signal also had to be tied to battery voltage for the controller to wake up."]].map(([Icon, title, text]) => { const ToolIcon = Icon as typeof BatteryCharging; return <div className="card-surface p-5" key={title as string}><ToolIcon className="h-5 w-5 text-[var(--accent)]" /><h3 className="mt-4 font-display text-lg font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{text as string}</p></div>; })}</div></div></FadeIn>
    <FadeIn delay={0.2}><section><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent)]">Build sheet</p><h2 className="mt-2 font-display text-3xl font-bold">The decisions that made it real</h2></div><Zap className="hidden h-7 w-7 text-[var(--accent)] sm:block" /></div><div className="overflow-hidden rounded-2xl border border-[var(--border)]"><div className="grid grid-cols-[0.7fr_1fr_1.6fr] border-b border-[var(--border)] bg-white/[0.04] px-4 py-3 text-xs font-bold uppercase tracking-[0.14em] text-[var(--muted)] md:px-6"><span>System</span><span>Choice</span><span>Why it mattered</span></div>{specs.map(([label, value, note]) => <div className="grid grid-cols-[0.7fr_1fr_1.6fr] border-b border-[var(--border)] px-4 py-4 text-sm last:border-b-0 md:px-6" key={label}><span className="font-semibold text-[var(--foreground)]">{label}</span><span className="font-mono text-[var(--accent)]">{value}</span><span className="text-[var(--muted)]">{note}</span></div>)}</div></section></FadeIn>
    <FadeIn delay={0.24}><div className="grid gap-8 lg:grid-cols-[1.15fr_0.85fr]"><section className="card-surface p-6 md:p-8"><div className="flex items-start gap-4"><Wrench className="mt-1 h-6 w-6 shrink-0 text-[var(--accent)]" /><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent)]">Field lessons</p><h2 className="mt-2 font-display text-2xl font-bold">The prototype taught back.</h2></div></div><ul className="mt-6 space-y-5 text-sm leading-6 text-[var(--muted)]"><li><strong className="text-[var(--foreground)]">Geometry beats optimism.</strong> The custom swingarm fit well, but the wheelbase ended up about 25 mm shorter than expected. A little more measurement before fabrication would have improved the final stance.</li><li><strong className="text-[var(--foreground)]">Big tires need a plan.</strong> Zip ties helped work the tubeless tire over the hub-motor rim; a ratchet strap and a burst of air helped seat it. The method worked, but it is a reminder to respect stored energy and use proper shop safety.</li><li><strong className="text-[var(--foreground)]">Packaging is part of the circuit.</strong> The 80/20 mockup made it possible to find a workable component arrangement before committing to final wiring. The electrical drawing and brake integration were still unfinished when testing stopped.</li></ul></section><section className="card-surface border-[var(--accent)]/30 p-6 md:p-8"><AlertTriangle className="h-6 w-6 text-amber-300" /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.18em] text-amber-300">Where the build paused</p><h2 className="mt-2 font-display text-2xl font-bold">The last ride changed the roadmap.</h2><p className="mt-4 text-sm leading-6 text-[var(--muted)]">After many successful rides, a driver making an illegal left turn hit the scooter head-on during a test ride at roughly 25 mph. The Vespa and rider both took significant damage, and the project went on hold. That is part of the build story too: a prototype is only successful if the person testing it gets home.</p></section></div></FadeIn>
    <FadeIn delay={0.28}><section className="card-surface overflow-hidden p-6 md:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent)]">Proof of life</p><h2 className="mt-2 font-display text-3xl font-bold">From wiring bench to moving machine</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--muted)]">The original build log includes the first motor rotation, first ride, and last ride. These clips are the most direct record of the conversion becoming real.</p></div><PlayCircle className="h-8 w-8 text-[var(--accent)]" /></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{[["First motor rotation", "https://youtu.be/M1-aNXbEMo8"], ["First ride", "https://youtu.be/-8GIeueYlfU"], ["Last ride", "https://youtu.be/zE-3BKzW_w0"]].map(([label, href]) => <a className="flex items-center justify-between rounded-xl border border-[var(--border)] bg-black/20 px-4 py-4 text-sm font-semibold transition-colors hover:border-[var(--accent)] hover:text-[var(--accent)]" href={href} target="_blank" rel="noopener noreferrer" key={label}><span>{label}</span><ExternalLink className="h-4 w-4" /></a>)}</div></section></FadeIn>
    <FadeIn delay={0.32}><div className="flex flex-col items-start justify-between gap-4 border-t border-[var(--border)] pt-8 sm:flex-row sm:items-center"><p className="max-w-2xl text-sm leading-6 text-[var(--muted)]">This page is an edited first-person build write-up based on the original documentation. The forum thread remains the source for the full photo sequence, CAD-file references, and discussion.</p><a href={SOURCE_URL} target="_blank" rel="noopener noreferrer" className="inline-flex shrink-0 items-center gap-2 rounded-lg border border-[var(--accent)]/40 px-4 py-2.5 text-sm font-semibold text-[var(--accent)] transition-colors hover:bg-[var(--accent-soft)]">Read the original thread <ExternalLink className="h-4 w-4" /></a></div></FadeIn>
  </Layout>;
}
