const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const arcadeDir = path.join(root, 'public/arcade/kestrel-heavy');
const arcadeHtml = fs.readFileSync(path.join(arcadeDir, 'index.html'), 'utf8');
const arcadeJs = fs.readFileSync(path.join(root, 'public/toolbox/js/arcade.js'), 'utf8');
const mission = fs.readFileSync(path.join(arcadeDir, 'js/mission.js'), 'utf8');
const storage = fs.readFileSync(path.join(arcadeDir, 'js/storage.js'), 'utf8');
const config = fs.readFileSync(path.join(arcadeDir, 'js/config.js'), 'utf8');
const input = fs.readFileSync(path.join(arcadeDir, 'js/input.js'), 'utf8');
const textures = fs.readFileSync(path.join(arcadeDir, 'js/textures.js'), 'utf8');
const missions = fs.readFileSync(path.join(arcadeDir, 'js/missions.js'), 'utf8');
const sequence = fs.readFileSync(path.join(arcadeDir, 'js/sequence.js'), 'utf8');
const storageDoc = fs.readFileSync(path.join(arcadeDir, 'STORAGE.md'), 'utf8');
const reactIndex = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const host = fs.readFileSync(path.join(root, 'src/components/games/KestrelHeavy.tsx'), 'utf8');
const pkg = fs.readFileSync(path.join(root, 'package.json'), 'utf8');
const mainJs = fs.readFileSync(path.join(arcadeDir, 'js/main.js'), 'utf8');
const hudJs = fs.readFileSync(path.join(arcadeDir, 'js/hud.js'), 'utf8');
const rootSw = fs.readFileSync(path.join(root, 'public/sw.js'), 'utf8');
const engineDoc = fs.readFileSync(path.join(arcadeDir, 'ENGINE.md'), 'utf8');
const vendorReadme = fs.readFileSync(path.join(arcadeDir, 'vendor/README.md'), 'utf8');
const vendorBuild = fs.readFileSync(path.join(arcadeDir, 'vendor/phaser.min.js'), 'utf8');
const syncPhaser = fs.readFileSync(path.join(root, 'scripts/sync-phaser.mjs'), 'utf8');

assert.match(pkg, /"phaser": "4\.2\.1"/);
assert.ok(fs.existsSync(path.join(arcadeDir, 'vendor/phaser.min.js')), 'Phaser 4 vendor build must be same-origin');
assert.match(vendorReadme, /Phaser 4\.2\.1/);
assert.match(vendorReadme, /phaser@4\.2\.1\/dist\/phaser\.min\.js/);
assert.match(vendorReadme, /Do \*\*not\*\* vendor `phaser-arcade-physics`/);
assert.match(engineDoc, /Phaser `4\.2\.1`/);
assert.match(engineDoc, /enableSleeping: true/);
assert.match(engineDoc, /this\.matter\.add/);
assert.match(engineDoc, /built-in Matter only/);
assert.match(syncPhaser, /4\.2\.1/);
assert.match(syncPhaser, /phaser-arcade-physics/);
assert.ok(vendorBuild.includes('Matter'), 'vendor must be the full Phaser build with Matter');
assert.ok(vendorBuild.length > 800000, 'vendor Phaser looks like an arcade-only slim build');
assert.doesNotMatch(vendorBuild.slice(0, 200), /phaser-arcade-physics/);
assert.match(arcadeHtml, /data-ng-engine="phaser4"/);
assert.match(arcadeHtml, /vendor\/phaser\.min\.js/);
assert.match(arcadeHtml, /type="module" src="\.\/js\/main\.js"/);
assert.doesNotMatch(arcadeHtml, /src="\/toolbox\/js\/arcade\.js"/);
assert.doesNotMatch(arcadeHtml, /arcadeCanvas/);
assert.match(arcadeHtml, /id="ng-phaser-root"/);
assert.match(arcadeHtml, /id="arcade-live"/);
assert.match(arcadeHtml, /aria-live="polite"/);
assert.match(arcadeHtml, /KID \/ CADET \/ PAD RAT/);
assert.match(arcadeHtml, /data-mission="KH-1"/);
assert.match(arcadeHtml, /data-mission="KH-5"/);
assert.match(arcadeHtml, /id="t-mission"/);
assert.match(arcadeHtml, /id="t-payload"/);
assert.match(arcadeHtml, /id="t-obj"/);
assert.match(arcadeHtml, /id="t-clock"/);
assert.match(arcadeHtml, /id="t-fuel"/);
assert.match(arcadeHtml, /id="t-mach"/);
assert.match(arcadeHtml, /id="t-q"/);
assert.match(arcadeHtml, /id="t-acc"/);
assert.match(arcadeHtml, /id="t-twr"/);
assert.match(arcadeHtml, /id="t-fpa"/);
assert.match(arcadeHtml, /id="t-sci"/);
assert.match(arcadeHtml, /id="ng-sum-why"/);
assert.match(arcadeHtml, /id="ng-pause-hint"/);
assert.match(arcadeHtml, /body\.is-kid \.sci-pro/);
assert.match(arcadeHtml, /names the reason/);
assert.match(arcadeHtml, /id="ng-play"/);
assert.match(arcadeHtml, />LAUNCH</);
assert.match(arcadeHtml, /id="ng-hold"/);
assert.match(arcadeHtml, /id="ng-open-missions"/);
assert.match(arcadeHtml, /id="ng-open-settings"/);
assert.match(arcadeHtml, /id="ng-open-howto"/);
assert.match(arcadeHtml, /cta-stack/);
assert.match(arcadeHtml, /cta-secondary/);
assert.match(arcadeHtml, /body\[data-phase="MENU"\] #ng-phaser-root/);
assert.match(arcadeHtml, /body\[data-phase="MENU"\] #ng-hints/);
assert.match(arcadeHtml, /background:\s*#070b14/);
assert.doesNotMatch(arcadeHtml, /TAP OR PRESS SPACE TO START PREFLIGHT/);
assert.doesNotMatch(mission, /TAP OR PRESS SPACE TO START PREFLIGHT/);
assert.doesNotMatch(mission, /TAP OR PRESS/);
assert.match(hudJs, /function syncPlayfieldPointers/);
assert.match(mission, /syncCanvasInput/);
assert.match(arcadeJs, /getElementById\('ng-menu'\)/);
assert.match(rootSw, /CACHE_VERSION = 'v6'/);
assert.match(rootSw, /\/arcade\//);
assert.match(rootSw, /EXCLUDED_PREFIXES[\s\S]*\/arcade\//);
assert.match(arcadeHtml, /name="arcade-asset-version" content="kestrel-6"/);
assert.match(arcadeHtml, /-webkit-touch-callout:\s*none/);
assert.match(arcadeHtml, /-webkit-user-select:\s*none/);
assert.match(arcadeHtml, /user-select:\s*none/);
assert.match(arcadeHtml, /-webkit-tap-highlight-color:\s*transparent/);
assert.match(arcadeHtml, /#arcade-touch-btns button \{\s*[\s\S]*?touch-action:\s*none/);
assert.match(arcadeHtml, /#ng-phaser-root[\s\S]*?touch-action:\s*none/);
assert.match(arcadeHtml, /content:\s*attr\(data-label\)/);
assert.match(arcadeHtml, /id="atb-boost"[^>]*aria-label="Hold boost to climb"/);
assert.match(arcadeHtml, /id="atb-boost"[^>]*data-label="HOLD TO CLIMB"/);
assert.match(arcadeHtml, /id="atb-left"[^>]*data-label="◀"/);
assert.match(arcadeHtml, /id="atb-right"[^>]*data-label="▶"/);
assert.doesNotMatch(arcadeHtml, /id="atb-boost"[^>]*>HOLD TO CLIMB</);
assert.match(hudJs, /addEventListener\('touchstart'/);
assert.match(hudJs, /addEventListener\('contextmenu'/);
assert.match(hudJs, /addEventListener\('selectstart'/);
assert.match(hudJs, /passive:\s*false/);
assert.match(hudJs, /dataset\.label = snapshot\.boostLabel/);
assert.match(input, /event\.code === 'Space'/);
assert.match(input, /event\.code === 'KeyA'/);
assert.match(host, /ARCADE_ASSET_VERSION = "kestrel-6"/);
assert.match(host, /index\.html\?v=\$\{ARCADE_ASSET_VERSION\}/);
assert.match(arcadeHtml, /id="ng-tape"/);
assert.match(arcadeHtml, /id="ng-phase"/);
assert.match(arcadeHtml, />SOUND</);
assert.match(arcadeHtml, />PAUSE</);
assert.match(arcadeHtml, />SET</);
assert.match(arcadeHtml, />FULL</);
assert.match(arcadeHtml, /viewport-fit=cover/);
assert.match(arcadeHtml, /--game-vv-height/);
assert.match(arcadeHtml, /aspect-ratio:\s*unset/);
assert.match(arcadeHtml, /arcade-host-fill/);
assert.match(arcadeHtml, /body\[data-phase="MENU"\] \.mc-hud/);
assert.match(arcadeHtml, /class="mc-callout"/);
assert.match(arcadeHtml, /grid-template-areas:[\s\S]*callout status score/);
assert.match(arcadeHtml, /class="mc-status"/);
assert.match(arcadeHtml, /class="mc-met"/);
assert.match(arcadeHtml, /#ng-hints[\s\S]*?bottom:\s*max\(5\.5rem/);
assert.doesNotMatch(arcadeHtml, /#ng-hints[\s\S]*?top:\s*46%/);
assert.match(arcadeHtml, /line-clamp:\s*2/);
assert.ok(
  arcadeHtml.indexOf('id="t-radio"') > arcadeHtml.indexOf('class="mc-callout"'),
  'voice radio must live in the offset callout, not the center MET stack',
);
assert.ok(
  arcadeHtml.indexOf('id="t-obj"') > arcadeHtml.indexOf('class="mc-callout"'),
  'objective must live in the offset callout, not the center MET stack',
);
assert.ok(
  arcadeHtml.indexOf('id="t-radio"') < arcadeHtml.indexOf('class="hud-btns"'),
  'callout radio stays inside the HUD overlay',
);
assert.match(fs.readFileSync(path.join(arcadeDir, 'js/fullscreen.js'), 'utf8'), /isIosPhone/);
assert.match(fs.readFileSync(path.join(arcadeDir, 'js/fullscreen.js'), 'utf8'), /isLetterboxed/);
assert.match(fs.readFileSync(path.join(arcadeDir, 'js/fullscreen.js'), 'utf8'), /usableViewportHeight/);
assert.match(fs.readFileSync(path.join(arcadeDir, 'js/fullscreen.js'), 'utf8'), /applyHostViewportMessage/);
assert.match(fs.readFileSync(path.join(arcadeDir, 'js/fullscreen.js'), 'utf8'), /beckify-kestrel-viewport/);
assert.match(mission, /shouldAttemptNativeFullscreen/);
assert.match(mission, /setArcadeCssImmersive/);
assert.match(mission, /requestHostViewport/);
assert.match(mainJs, /visualViewport/);
assert.match(fs.readFileSync(path.join(root, 'public/arcade/index.html'), 'utf8'), /games\/kestrel-heavy/);
assert.match(arcadeHtml, /id="t-shield"/);
assert.match(arcadeHtml, /id="ng-pause-restart"/);
assert.match(arcadeHtml, /id="ng-sum-next"/);
assert.match(arcadeHtml, /id="ng-launch-tip"/);
assert.match(arcadeHtml, /id="ng-card-flight"/);
assert.match(arcadeHtml, /manifest-row/);
assert.match(arcadeHtml, /body\.is-embedded #arcade-fullscreen-btn/);
assert.match(arcadeHtml, /id="ng-summary"/);
assert.match(arcadeHtml, /data-arcade-standalone/);
assert.doesNotMatch(arcadeHtml, /role="img"/);
assert.doesNotMatch(arcadeHtml, /cdn\.jsdelivr\.net/);
assert.match(arcadeHtml, /fonts\.googleapis\.com.*Exo\+2/);
assert.match(arcadeHtml, /IBM\+Plex\+Mono/);
assert.match(arcadeHtml, /prefers-reduced-motion/);

assert.match(config, /STORAGE_KEY = 'newGlennRunnerStateV6'/);
assert.match(config, /newGlennRunnerStateV5/);
assert.match(config, /newGlennRunnerStateV4/);
assert.match(config, /newGlennRunnerStateV3/);
assert.match(config, /newGlennRunnerSettingsV2/);
assert.match(config, /sfxVolume/);
assert.match(config, /musicVolume/);
assert.match(config, /controlHints/);
assert.match(config, /launchTipSeen/);
assert.match(config, /BOOST_COYOTE_SEC = 0\.14/);
assert.match(config, /BOOST_BUFFER_SEC = 0\.18/);
assert.match(config, /PICKUP_TYPES = \['shield', 'fuel', 'boost'\]/);
assert.match(storage, /newGlennRunnerStateV6/);
assert.match(storage, /newGlennRunnerStateV5/);
assert.match(storage, /newGlennRunnerStateV4/);
assert.match(storage, /newGlennRunnerStateV3/);
assert.match(input, /function isBoosting\(/);
assert.match(input, /function consumeBoostTap\(/);
assert.match(input, /function clearFlightHolds\(/);
assert.match(input, /Escape/);
assert.match(input, /visibilitychange/);
assert.match(input, /blur/);

assert.match(mainJs, /physics:\s*\{[\s\S]*default:\s*'matter'/);
assert.match(mainJs, /enableSleeping:\s*true/);
assert.match(mainJs, /Phaser\.Scale\.FIT/);
assert.match(mainJs, /Phaser\.Scale\.ENVELOP/);
assert.match(mainJs, /Phaser\.Scale\.CENTER_BOTH/);
assert.match(mainJs, /Phaser\.WEBGL/);
assert.match(mainJs, /get\('debug'\) === '1'/);
assert.doesNotMatch(mainJs, /from ['"]phaser-arcade-physics['"]/);
assert.match(mainJs, /Never swap in phaser-arcade-physics/);
assert.doesNotMatch(mission, /Matter\.Engine/);
assert.doesNotMatch(mission, /new Matter\./);
assert.match(mission, /this\.matter\.add\.image/);
assert.match(mission, /this\.matter\.add\.rectangle/);
assert.match(mission, /setTexture\('booster'\)[\s\S]{0,80}bindRocketBody\(\)/);
assert.match(mission, /this\.matter\.pause\(\)/);
assert.match(mission, /this\.matter\.resume\(\)/);
assert.match(mission, /syncMatterPause/);
assert.match(mission, /paused === true/);
assert.match(mission, /CAT_DECK/);
assert.match(mission, /CAT_WATER/);
assert.match(mission, /isSensor:\s*true/);
assert.match(mission, /landingVy/);
assert.match(mission, /this\.matter/);
assert.match(mission, /JACKLYN/);
assert.match(mission, /BOOSTER RECOVERED/);
assert.match(mission, /jacklynPhase/);
assert.match(mission, /jacklynReadyAt/);
assert.match(mission, /HAVEN\.zoomFar/);
assert.match(mission, /frameHavenCamera/);
assert.match(mission, /recordGameScore\('kestrel-heavy'/);
assert.match(mission, /hiArcadeScore/);
assert.match(mission, /beat === 'haven'|isHavenQa/);
assert.match(mission, /qaBeat === 'sep'/);
assert.match(mission, /beat=jacklyn|qaBeat/);
assert.match(missions, /id: 'KH-1'/);
assert.match(missions, /id: 'KH-5'/);
assert.match(missions, /Aether Scout/);
assert.match(missions, /Ember Pair/);
assert.match(storageDoc, /newGlennRunnerStateV6/);
assert.match(storageDoc, /newGlennRunnerStateV5/);
assert.match(sequence, /TERMINAL COUNT/);
assert.match(sequence, /TANK PRESS/);
assert.match(sequence, /INTERNAL POWER/);
assert.match(sequence, /WATER DELUGE/);
assert.match(sequence, /IGNITION/);
assert.match(sequence, /LIFTOFF/);
assert.match(sequence, /MAX-Q/);
assert.match(sequence, /MECO/);
assert.match(sequence, /STAGE SEP/);
assert.match(sequence, /SES-1/);
assert.match(sequence, /FAIRING JETTISON/);
assert.match(sequence, /ENTRY BURN/);
assert.match(sequence, /LANDING BURN/);
assert.match(sequence, /HAVEN TOUCHDOWN/);
assert.match(sequence, /SECO/);
assert.match(sequence, /PAYLOAD DEPLOY/);
assert.match(mission, /beatsFor/);
assert.match(mission, /formatClock/);
assert.match(mission, /phaseChip/);
assert.match(mission, /clearFlightHolds/);
assert.match(mission, /kestrelHaptics/);
assert.match(mission, /restartMission/);
assert.match(mission, /ascentScore/);
assert.match(mission, /launchTipSeen/);
assert.match(mission, /STANDBY/);
assert.match(sequence, /function phaseChip/);
assert.match(mission, /PRELAUNCH/);
assert.match(mission, /playStageSep/);
assert.match(mission, /enterSep/);
assert.match(mission, /updateSep/);
assert.match(mission, /fireSep/);
assert.match(mission, /status === 'SEP'/);
assert.match(mission, /ALIGN GREEN/);
assert.match(mission, /applyHavenDrift/);
assert.match(mission, /landingTol/);
assert.match(mission, /TIP_PENALTY/);
assert.match(config, /export const PACE/);
assert.match(config, /export const SEP/);
assert.match(config, /export const HAVEN/);
assert.match(config, /export const CAM/);
assert.match(config, /ascentStart: 0\.56/);
assert.match(config, /zoomFar: 0\.34/);
assert.match(config, /sepAlignDeg/);
assert.match(config, /wind:/);
assert.match(config, /JACKLYN_BONUS = 2800/);
assert.match(config, /SPLASH_PENALTY = 1200/);
assert.match(sequence, /PACE\.MECO/);
assert.match(sequence, /ALIGN then TAP CLIMB/);
assert.match(arcadeHtml, /beat=haven/);
assert.match(arcadeHtml, /beat=sep/);
assert.match(engineDoc, /beat=haven/);
assert.match(engineDoc, /legacy alias/);
assert.doesNotMatch(arcadeHtml, /Blue Origin|New Glenn|Jacklyn|LC-36|BE-4/);
assert.doesNotMatch(missions, /Blue Origin|New Glenn|Jacklyn|LC-36|BE-4/);
assert.match(host, /aspect-video/);
assert.match(host, /ng-playfield/);
assert.match(host, /is-immersive/);
assert.match(host, /absolute inset-0/);
assert.match(fs.readFileSync(path.join(root, 'src/pages/kestrel-heavy.tsx'), 'utf8'), /variant="cabinet"/);
assert.doesNotMatch(host, /min-h-\[min\(360px/);
assert.doesNotMatch(mission, /label:\s*"Apollo"/);
assert.doesNotMatch(mission, /label:\s*"Rocco"/);
assert.doesNotMatch(mission, /temple run/i);
assert.doesNotMatch(mission, /babylon/i);
assert.doesNotMatch(mission, /THREE\./);

assert.match(textures, /drawIlt/);
assert.match(textures, /drawLaunchTable/);
assert.match(textures, /drawGse/);
assert.doesNotMatch(textures, /leftTowerX/);
assert.doesNotMatch(textures, /rightTowerX/);
assert.match(textures, /function makeAscentSky\(/);
assert.match(textures, /function makeStarfield\(/);
assert.match(textures, /function makeCloudSheet\(/);
assert.match(textures, /function makeHazeBand\(/);
assert.match(textures, /function makeSepShard\(/);
assert.match(textures, /add\('stars'/);
assert.match(textures, /add\('clouds-far'/);
assert.match(textures, /function drawIlt\(/);
assert.match(textures, /createRadialGradient\(1080/);
assert.match(textures, /function makeBooster\(/);
assert.match(textures, /function makeSmokeBank\(/);
assert.match(textures, /function makeBloom\(/);
assert.match(textures, /deck-pad/);
assert.match(textures, /HAVEN/);
assert.match(textures, /solid black strakes/);
assert.match(textures, /lattice grid fins/);
assert.match(textures, /REJECT Falcon cues/);
assert.match(textures, /ASDS circle-X/);
assert.doesNotMatch(textures, /makeGridFin|gridFin|latticeFin/);
assert.doesNotMatch(textures, /booster-legs/);
assert.doesNotMatch(mission, /booster-legs/);
assert.match(mission, /playRecoveredSpectacle/);
assert.match(mission, /flashPad/);

assert.match(arcadeJs, /ng-phaser-root/);
assert.match(arcadeJs, /dataset\.ngEngine === 'phaser4'/);

assert.match(reactIndex, /frame-src 'self'/);
assert.match(host, /arcade\/kestrel-heavy\/index\.html/);
assert.match(host, /title="Kestrel Heavy"/);
assert.match(host, /max-w-\[1280px\]/);
assert.doesNotMatch(host, /max-w-\[1100px\]/);
assert.doesNotMatch(host, /sandbox=/);
assert.doesNotMatch(host, /scrolling=/);
assert.doesNotMatch(host, /max-w-\[520px\]/);
assert.match(arcadeHtml, /max-width:\s*1280px/);
assert.match(arcadeHtml, /data-ng-engine="phaser4"/);
assert.doesNotMatch(arcadeHtml, /src="\.\/js\/arcade\.js"/);

const audioJs = fs.readFileSync(path.join(arcadeDir, 'js/audio.js'), 'utf8');
const audioAttr = fs.readFileSync(path.join(arcadeDir, 'audio/ATTRIBUTION.md'), 'utf8');
const audioDir = path.join(arcadeDir, 'audio');
const audioClips = [
  'roar-loop', 'liftoff', 'maxq', 'meco', 'whoosh', 'burn-loop',
  'touchdown', 'recovered', 'splash', 'quindar', 'pickup', 'hit', 'rud',
  'theme',
];
for (const clip of audioClips) {
  assert.ok(fs.existsSync(path.join(audioDir, `${clip}.ogg`)), `${clip}.ogg`);
  assert.ok(fs.existsSync(path.join(audioDir, `${clip}.mp3`)), `${clip}.mp3`);
}
assert.match(audioJs, /preload\(scene\)/);
assert.match(audioJs, /scene\.load\.audio/);
assert.match(audioJs, /audio\/\$\{THEME\.file\}\.ogg|audio\/theme\.ogg/);
assert.match(audioJs, /ng-\$\{THEME\.file\}|ng-theme/);
assert.match(audioJs, /setTheme/);
assert.match(audioJs, /duckTheme/);
assert.match(audioJs, /sound\.unlock/);
assert.match(audioJs, /sound\.setMute/);
assert.match(audioJs, /prefers-reduced-motion never mutes/);
assert.doesNotMatch(audioJs, /blue origin|youtube/i);
assert.match(mission, /AudioApi\.preload\(this\)/);
assert.match(mission, /setTheme\(true/);
assert.match(audioAttr, /suno\.com\/s\/nQE6Wpy3HGO0uYbH/);
assert.match(audioAttr, /trevorjohnbeck/);
assert.match(audioAttr, /9d457ba9-2ff4-40b1-9bfa-9eed22f90743/);
assert.match(mission, /setBed\('roar'/);
assert.match(mission, /setBed\('burn'/);
assert.match(mission, /play\('whoosh'/);
assert.match(mission, /play\('recovered'/);
assert.match(config, /volume: 0\.72/);
assert.match(arcadeHtml, /data-set="volume"/);
assert.match(arcadeHtml, /data-set="sfxVolume"/);
assert.match(arcadeHtml, /data-set="musicVolume"/);
assert.match(audioAttr, /nasa\.gov\/artemisaudio/);
assert.match(audioAttr, /nasa\.gov\/historical-sounds/);
assert.match(audioAttr, /No NASA endorsement is implied/);
assert.match(audioAttr, /590189main_ringtone_131_launchNats/);
assert.doesNotMatch(audioAttr, /blueorigin|youtu\.be|youtube\.com/i);
assert.match(storageDoc, /volume.*0–1/);

const voiceJs = fs.readFileSync(path.join(arcadeDir, 'js/voice.js'), 'utf8');
const telemetryJs = fs.readFileSync(path.join(arcadeDir, 'js/telemetry.js'), 'utf8');
assert.match(voiceJs, /export const LINES/);
assert.match(voiceJs, /export const ABORTS/);
assert.match(voiceJs, /export function speak/);
assert.match(voiceJs, /export function createVoice/);
assert.match(voiceJs, /hint-ascent/);
assert.match(voiceJs, /align-green/);
assert.match(voiceJs, /Propellant starved/);
assert.match(voiceJs, /Max-Q structural/);
assert.doesNotMatch(voiceJs, /Blue Origin|New Glenn|Jacklyn|LC-36|BE-4/);
assert.doesNotMatch(telemetryJs, /Blue Origin|New Glenn|Jacklyn|LC-36|BE-4/);
assert.match(telemetryJs, /export function computeTelemetry/);
assert.match(telemetryJs, /export function formatScience/);
assert.match(telemetryJs, /qKpa/);
assert.match(telemetryJs, /mach/);
assert.match(mission, /from '\.\/voice\.js'/);
assert.match(mission, /from '\.\/telemetry\.js'/);
assert.match(mission, /failFlight/);
assert.match(mission, /markOutcome/);
assert.match(mission, /setSummaryWhy/);
assert.match(mission, /callout\('hint-ascent'/);
assert.match(mission, /callout\('hint-sep'/);
assert.match(mission, /callout\('hint-haven'/);
assert.match(mission, /CAM\.ascentStart/);
assert.match(mission, /alignRadio/);
assert.match(hudJs, /t-mach/);
assert.match(hudJs, /function setSummaryWhy/);
assert.match(hudJs, /if \(text && !same\) announce/);

const iosRoot = path.join(root, '../../ios');
const iosGame = path.join(iosRoot, 'KestrelHeavy/Game');
assert.ok(fs.existsSync(path.join(iosGame, 'index.html')), 'iOS Game pack must ship index.html');
const iosHtml = fs.readFileSync(path.join(iosGame, 'index.html'), 'utf8');
assert.doesNotMatch(iosHtml, /\/toolbox\/js\//);
assert.match(iosHtml, /viewport-fit=cover/);
assert.match(iosHtml, /is-ios-app/);
assert.doesNotMatch(iosHtml, /fonts\.googleapis\.com/);
assert.ok(fs.existsSync(path.join(iosGame, 'vendor/phaser.min.js')), 'iOS pack must vendor Phaser');
assert.ok(fs.existsSync(path.join(iosGame, 'audio/theme.mp3')), 'iOS pack must include theme BGM');
const pbx = fs.readFileSync(path.join(iosRoot, 'Beckify.xcodeproj/project.pbxproj'), 'utf8');
assert.match(pbx, /PRODUCT_BUNDLE_IDENTIFIER = com\.beckify\.kestrelheavy/);
assert.match(pbx, /name = KestrelHeavy/);
assert.match(pbx, /KestrelHeavySchemeHandler\.swift/);
assert.match(fs.readFileSync(path.join(iosRoot, 'KestrelHeavy/KestrelHeavyGameView.swift'), 'utf8'), /setURLSchemeHandler/);
assert.match(fs.readFileSync(path.join(iosRoot, 'KestrelHeavy/KestrelHeavyGameView.swift'), 'utf8'), /webViewWebContentProcessDidTerminate/);
assert.match(fs.readFileSync(path.join(iosRoot, 'KestrelHeavy/KestrelHeavySchemeHandler.swift'), 'utf8'), /kestrel-heavy:\/\/game\/index\.html/);
const khConfigs = pbx.split('KHCF00000000000000000013 /* Debug */')[1].split('/* End XCBuildConfiguration')[0];
assert.match(khConfigs, /UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight/);
assert.doesNotMatch(khConfigs, /UIInterfaceOrientationPortrait /);
assert.match(fs.readFileSync(path.join(iosRoot, 'Beckify.xcodeproj/xcshareddata/xcschemes/KestrelHeavy.xcscheme'), 'utf8'), /KestrelHeavy\.app/);
assert.doesNotMatch(fs.readFileSync(path.join(iosRoot, 'Beckify/Models/ToolboxCatalog.swift'), 'utf8'), /kestrel/i);

console.log('Kestrel Heavy Phaser 4 path, Haven recovery, and iframe host checks passed');
