const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const arcade = fs.readFileSync(path.join(root, 'public/toolbox/js/arcade.js'), 'utf8');
const arcadeHtml = fs.readFileSync(path.join(root, 'public/arcade/new-glenn-runner/index.html'), 'utf8');
const reactIndex = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const host = fs.readFileSync(path.join(root, 'src/components/games/NewGlennRunner.tsx'), 'utf8');

assert.match(arcade, /const BOOST_COYOTE_SEC = 0\.14/);
assert.match(arcade, /const BOOST_BUFFER_SEC = 0\.18/);
assert.match(arcade, /function isBoosting\(/);
assert.match(arcade, /function consumeBoostTap\(/);
assert.match(arcade, /function updateInputFeel\(/);
assert.match(arcade, /function updateFlightHazards\(/);
assert.match(arcade, /if \(updateFlightHazards\(dt, 'maxq'\)\) return/);
assert.match(arcade, /if \(updateFlightHazards\(dt, 'ascent'\)\) return/);
assert.match(arcade, /const PICKUP_TYPES = \['shield', 'fuel', 'boost'\]/);
assert.match(arcade, /function tryAbsorbHit\(/);
assert.match(arcade, /function spawnPickup\(/);
assert.match(arcade, /hiArcadeScore/);
assert.match(arcade, /recordGameScore\('new-glenn-runner', points\)/);
assert.match(arcade, /Audio\.stopMusic\(\)/);
assert.match(arcade, /announce\(/);
assert.match(arcade, /arcade-live/);
assert.match(arcade, /function beginJacklynLanding\(/);
assert.match(arcade, /function updateJacklynLanding\(/);
const seaPhaseIncrements = arcade.match(/state\.effects\.seaPhase \+= dt/g) || [];
assert.equal(seaPhaseIncrements.length, 1, 'seaPhase must increment once per frame (updateMission only)');
assert.match(arcade, /function resolveJacklynTouchdown\(/);
assert.match(arcade, /function drawJacklynOcean\(/);
assert.match(arcade, /BOOSTER RECOVERED/);
assert.match(arcade, /landing barge/);
assert.match(arcade, /TIP ON DECK/);
assert.match(arcade, /SPLASHDOWN/);
assert.match(arcade, /Mission continues/);
assert.match(arcade, /CLOSE CALL/);
assert.match(arcade, /ASCENT_FIRST_HAZARD_AT/);
assert.match(arcade, /startSlowMo\(/);
assert.match(arcade, /HOLD TO BRAKE/);
assert.match(arcade, /get\('beat'\) === 'jacklyn'/);
assert.match(arcade, /function drawIntegratedLaunchTower\(/);
assert.match(arcade, /function drawLaunchTable\(/);
assert.match(arcade, /function drawPropellantGse\(/);
assert.match(arcade, /const CW = 960/);
assert.match(arcade, /const CH = 540/);
assert.match(arcade, /const PAD_ILT_X = Math.round\(CW \* 0\.70\)/);
assert.match(arcade, /function isCompactHud\(/);
assert.match(arcade, /function hudMono\(/);
assert.match(arcade, /TELEMETRY/);
assert.match(arcade, /Integrated Launch Tower/);
assert.doesNotMatch(arcade, /leftTowerX/);
assert.doesNotMatch(arcade, /rightTowerX/);
assert.doesNotMatch(arcade, /quadraticCurveTo\(CW \/ 2, towerTopY/);
assert.doesNotMatch(arcade, /"VT323"/);
assert.doesNotMatch(arcade, /Share Tech Mono/);
assert.match(arcade, /IBM Plex Mono/);
assert.match(arcade, /Exo 2/);
assert.match(arcade, /prefers-reduced-motion/);
assert.match(arcade, /e\.code === 'Escape'/);
assert.doesNotMatch(arcade, /temple run/i);
assert.doesNotMatch(arcade, /label:\s*"Apollo"/);
assert.doesNotMatch(arcade, /label:\s*"Rocco"/);

assert.match(arcadeHtml, /data-arcade-standalone/);
assert.match(arcadeHtml, /KID \/ CADET \/ PAD RAT/);
assert.match(arcadeHtml, /Jacklyn/);
assert.match(arcadeHtml, /<h1 class="visually-hidden">New Glenn Runner<\/h1>/);
assert.match(arcadeHtml, /id="arcade-live"/);
assert.doesNotMatch(arcadeHtml, /role="img"/);
assert.match(arcade, /beforeScore = arcadeScore\(\)/);
assert.match(arcadeHtml, /aria-live="polite"/);
assert.match(arcadeHtml, /src="\/toolbox\/js\/arcade\.js"/);
assert.match(arcadeHtml, /src="\/toolbox\/js\/local-store\.js"/);
assert.match(arcadeHtml, /fonts\.googleapis\.com.*Exo\+2/);
assert.match(arcadeHtml, /IBM\+Plex\+Mono/);
assert.doesNotMatch(arcadeHtml, /cdn\.jsdelivr\.net/);
assert.match(arcadeHtml, /width="960"/);
assert.match(arcadeHtml, /height="540"/);
assert.match(arcadeHtml, /max-width:\s*1100px/);
assert.match(arcadeHtml, /in-embed/);

assert.match(reactIndex, /frame-src 'self'/);
assert.match(host, /arcade\/new-glenn-runner\/index\.html/);
assert.match(host, /title="New Glenn Runner"/);
assert.match(host, /max-w-\[1100px\]/);
assert.doesNotMatch(host, /sandbox=/);
assert.doesNotMatch(host, /scrolling=/);

console.log('New Glenn Runner play-pass systems and iframe host checks passed');
