// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/games-usability/AccessibleReadable.tsx": () => import("../components/mockups/games-usability/AccessibleReadable.tsx"),
  "./components/mockups/games-usability/AffordanceFirst.tsx": () => import("../components/mockups/games-usability/AffordanceFirst.tsx"),
  "./components/mockups/games-usability/InformationHierarchy.tsx": () => import("../components/mockups/games-usability/InformationHierarchy.tsx")
};
