/**
 * ============================================================================
 * CALC FORM
 * ============================================================================
 * Render a calculator form from a CalcSpec: input fields, compute button,
 * results display. Handles form state and validation.
 * ============================================================================
 */

import { useState, useCallback } from "react";
import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { NumberField, SelectField } from "./NumberField";
import { ResultCard } from "./ResultCard";
import type { CalcSpec, Values } from "@/lib/ee/types";

interface CalcFormProps {
  spec: CalcSpec;
}

function exportReport(spec: CalcSpec, values: Values, result: ReturnType<CalcSpec["compute"]>) {
  const now = new Date().toLocaleString("en-US", { timeZoneName: "short" });
  const lines: string[] = [
    "BECKIFY ENGINEERING CALCULATOR REPORT",
    "=".repeat(50),
    `Tool:      ${spec.name}`,
    `Category:  ${spec.category}`,
    `Date:      ${now}`,
    "",
  ];

  if (spec.formula) {
    lines.push("FORMULA", "-".repeat(30), spec.formula, "");
  }

  if (spec.reference) {
    lines.push("REFERENCE", "-".repeat(30), spec.reference, "");
  }

  lines.push("INPUTS", "-".repeat(30));
  spec.fields.forEach((f) => {
    const val = values[f.id];
    if (val !== undefined && val !== "") {
      const unit = f.unit ? ` ${f.unit}` : "";
      lines.push(`  ${f.label}: ${val}${unit}`);
    }
  });
  lines.push("");

  if (result?.error) {
    lines.push("RESULT", "-".repeat(30), `ERROR: ${result.error}`, "");
  } else if (result && result.rows.length > 0) {
    lines.push("RESULTS", "-".repeat(30));
    result.rows.forEach((row) => {
      const unit = row.unit ? ` ${row.unit}` : "";
      lines.push(`  ${row.label}: ${row.value}${unit}`);
      if (row.note) lines.push(`    Note: ${row.note}`);
    });
    lines.push("");
  }

  lines.push(
    "ENGINEERING NOTES",
    "-".repeat(30),
    "All calculations performed per IEEE/ANSI/NEC standards where applicable.",
    "Verify results against current code edition before use in engineering documents.",
    "",
    "Generated by Beckify — beckify.com",
  );

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `beckify-${spec.id}-${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function CalcForm({ spec }: CalcFormProps) {
  const [values, setValues] = useState<Values>(
    Object.fromEntries(spec.fields.map((f) => [f.id, f.default || ""]))
  );
  const [result, setResult] = useState(spec.compute(values));
  const [error, setError] = useState<string>();

  const handleFieldChange = useCallback((fieldId: string, value: string) => {
    setValues((prev) => ({ ...prev, [fieldId]: value }));
  }, []);

  const handleCompute = useCallback(() => {
    try {
      setError(undefined);
      const newResult = spec.compute(values);
      setResult(newResult);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Calculation error");
      setResult(null);
    }
  }, [spec, values]);

  // Require at least one filled field; solvers handle "insufficient data" themselves
  const visibleFields = spec.fields.filter(
    (f) => !f.showIf || f.showIf(values)
  );
  const filledCount = visibleFields.filter(
    (f) => values[f.id] !== undefined && values[f.id] !== ""
  ).length;
  const isComplete = filledCount >= 1;

  const hasGoodResult = result && result.rows.length > 0 && !result.error;

  return (
    <div className="space-y-6">
      <form
        onSubmit={(e) => {
          e.preventDefault();
          handleCompute();
        }}
        className="space-y-4"
      >
        <div
          className={`grid gap-4 ${
            visibleFields.some((f) => f.full) ? "grid-cols-1" : "grid-cols-1 sm:grid-cols-2"
          }`}
        >
          {visibleFields.map((field) => (
            <div
              key={field.id}
              className={field.full ? "col-span-full" : ""}
            >
              {field.type === "select" ? (
                <SelectField
                  field={field}
                  value={values[field.id] || ""}
                  onChange={(v) => handleFieldChange(field.id, v)}
                />
              ) : (
                <NumberField
                  field={field}
                  value={values[field.id] || ""}
                  onChange={(v) => handleFieldChange(field.id, v)}
                />
              )}
            </div>
          ))}
        </div>

        {spec.formula && (
          <div className="p-3 rounded-lg bg-[var(--surface)] border border-[var(--border)]">
            <p className="text-xs uppercase tracking-wider font-semibold text-[var(--muted)] mb-1">
              Formula
            </p>
            <p className="font-mono text-sm text-[var(--foreground)] break-all">
              {spec.formula}
            </p>
          </div>
        )}

        <div className="flex gap-2">
          <Button
            type="submit"
            disabled={!isComplete}
            className="flex-1"
          >
            {spec.cta || "Calculate"}
          </Button>

          {hasGoodResult && (
            <Button
              type="button"
              variant="outline"
              size="icon"
              title="Export Report"
              aria-label="Export calculation report"
              onClick={() => result && exportReport(spec, values, result)}
            >
              <Download className="w-4 h-4" />
            </Button>
          )}
        </div>
      </form>

      {result && <ResultCard result={result} error={error} />}
    </div>
  );
}
